### ISSUE TITLE
Meta: Variablennamen

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#102]
Die Variablennamen sollen ausgeschrieben werden und auch in den Docs entsprechend angepasst werden.

**Comment by nclskfm** [comment]
is das noch aktuell?

**Comment by jstsddg** [comment]
Ich glaube schon. Hatte er sich nicht auch beim letzten Mal wieder darüber beschwert?

**Comment by nclskfm** [comment]
hab ich mir nicht aufgeschrieben. Und ich meine wir verwenden konsistent `s` als `state` und `p` als `player`. Wüsste nicht, warum wir das ausformulieren sollten. Zumal jede Variable kommentiert ist.

**Comment by jstsddg** [comment]
Nach Rücksprache mit @nclskfm wird das Issue geschlossen, da nur `s` und `p` übrig sind.
