### ISSUE TITLE
Meta: objektivieren Maßstab entwickeln

### ISSUE THREAD

**Issue by benfu99** [nclskfm/dhbw-studienarbeit-muehle#136]
Es soll ein objektiver Maßstab gefunden werden um zwei verschiedene Versionen vergleichen zu können

**Comment by jstsddg** [comment]
Am simpelsten wäre es, wenn wir alles konfigurierbar machen und dann die KIs mehrmals gegeneinander Spielen lassen. Hierzu würde ich folgende Schritte vorschlagen:
* Gewichtungen in der Heuristik konfigurierbar machen (Implementiert in #142)
* Eigenschaften in AlphaBetaPruning / Minimax konfigurierbar machen (`limit`, `moveOrdering`: an / aus, etc.)
  * Ein gesammeltes Konfigurationsobjekt (wie in #142) wäre wahrscheinlich am einfachsten.
* Damit der Cache zwischen Algorithmen (vor allem wegen verschiedenen Heuristiken) nicht geteilt wird, würde ich ein `Runtime` Objekt oder ähnliches vorschlagen. Dieses Objekt speichert den Cache, die Einstellungen und weiteres für jede Algorithmen Instanz. Ähnlich wie in meiner [Rust Implementierung](https://github.com/jstsddg/nine-mens-morris/blob/main/src/artificial_intelligence/minimax.rs).
  * Auf diesen Objekten sollte dann die Funktion `bestMoves` implementiert sein.
* Im Zuge dieser Anpassung kann dann auch #131 Implementiert werden:
  * `bestMoves` gibt alle besten Züge (mit der gleichen `value`) zurück.
  * `bestMove` gibt einen zufälligen Zug aus `bestMoves` zurück.

**Comment by nclskfm** [comment]
@jstsddg Klingt auf jeden Fall sinnvoll und hätte ich ähnlich gemacht. :)

> Damit der Cache zwischen Algorithmen (vor allem wegen verschiedenen Heuristiken) nicht geteilt wird, würde ich ein Runtime Objekt oder ähnliches vorschlagen. Dieses Objekt speichert den Cache, die Einstellungen und weiteres für jede Algorithmen Instanz. Ähnlich wie in meiner Rust Implementierung.

Das hätte ich ein bisschen simpler gelöst (einfach für die gemeinsamen Versuche ein gemeinsamen Cache, wo man die Referenz bei einem Aufruf mitgeben kann). Aber Runtime Objekt klingt auf jeden Fall seriöser :joy:

**Comment by jstsddg** [comment]
Ich bin mir nicht ganz sicher, wie genau du das mit deinem zweiten Kommentar meinst, aber gefühlt könnte es sein, dass das nicht funktioniert, weil ja die Heuristik unterschiedlich sein kann und somit falsche Werte im Cache landen würden. Kann aber sein, dass du das mit der Referenz irgendwie lösen wolltest.

**Comment by jstsddg** [comment]
Mit den Ergebnissen aus #146 sollte ein objektiver Maßstab / ein Vergleich möglich sein.
