### ISSUE TITLE
AI: play_game

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#17]
Eine Funktion, die es ermöglicht das Spiel mit der GUI gegen den Algorithmus (`minimax`, `alphaBeta`-Pruning) zu spielen.

**Comment by jstsddg** [comment]
@nclskfm Meinst du, dass du mit der GUI weit genug kommst, dass wir das implementieren können?

**Comment by nclskfm** [comment]
Ja ich wollte die Woche damit anfangen und bis Weihnachten soweit fertig sein

**Comment by jstsddg** [comment]
Genial, dann füge ich dem Milestone die Issues hinzu :)

**Comment by benfu99** [comment]
@jstsddg @nclskfm Ist das Issue noch realistisch für diesen Milestone oder wollen wir es verschieben?

**Comment by jstsddg** [comment]
Uff, muss gaube ich eher @nclskfm sagen wie einfach das in der GUI zu implementieren ist. Im Minimax algorithmus muss da eigentlich nichts mehr gemacht werden außer den Bugfixes, die ich gerade zum Review geschickt habe

**Comment by nclskfm** [comment]
Öhm weiß ich grad auch nicht. :D
Tendenziell eher verschieben, aber ich schau es mir morgen früh nochmal an.

**Comment by jstsddg** [comment]
@nclskfm Hab's jetzt mal verschoben :P
