### ISSUE TITLE
Tunier: Funktioniert nicht unter Windows (multiprocessing)

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#221]
Das `multiprocessing` Package funktioniert zwar unter Windows, aber anscheinend nicht in Jupyter. Hier sollte mal geschaut werden, ob es einen Fix dafür gibt.

**Comment by benfu99** [comment]
Ansatz 1: multiprocess statt multiprocessing

Der Import der Notebooks funktioniert nicht, da die gestarteten Prozesse nicht mit IPython, sondern mit python ausgeführt wurden. Leider existiert für mutliprocess praktisch keine Dokumentation.

Ansatz 2: execute-Funktion auslagern

Sah vielversprechend aus, leider lassen sich keine notebooks in normale python scripte importieren. Das heißt, man müsste alle Notebooks in .py Dateien umwandeln. Das ist mir zu aufwändig
