### ISSUE TITLE
Tunier: AlphaBetaPruning mit und ohne Iterative Deepening

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#222]
Ein Tunier zwischen AlphaBetaPruning mit und ohne Iterative Deepening könnten sehr interessant sein. Wenn noch Zeit ist, könnte dies einmal implementiert werden.

**Comment by jstsddg** [comment]
Da wir schon recht viel Zeit in das `multiprocessing` Problem gesteckt haben, würde ich dieses Issue tatsächlich nicht bearbeiten, was ist eure Meinung dazu?

@benfu99 @nclskfm

**Comment by nclskfm** [comment]
bin ich d'accord mit

**Comment by benfu99** [comment]
jup, klingt vernünftig
