### ISSUE TITLE
Bug: Unendliche nextStates in Phase 3

### ISSUE THREAD

**Issue by benfu99** [nclskfm/dhbw-studienarbeit-muehle#29]
In Phase 3 des Spiels kommt es dazu, dass auch neue nextStates generiert werden, auch wenn ein Spieler weniger als 3 Steine hat und somit verloren hat

**Comment by jstsddg** [comment]
Ist das wirklich ein Bug? Es gibt ja die Funktion `finished(s)`, die den Fall eigentlich vorher abfangen sollte. Oder verstehe ich das falsch?

**Comment by benfu99** [comment]
Naja, wie man es sieht. Auf jeden Fall ist mir aufgefallen bei der Programmierung von Minimax: value, dass er immer in eine Endlosrekursion kommt. Das liegt entweder daran, weil in der Phase3 nicht abgefangen wird, oder weil in der finished Funktion nicht abgefangen wird

**Comment by benfu99** [comment]
Ich hätte es jetzt in die nextStates Funktion integriert, weil die ja so oder so keine nextStates generieren soll, wenn ein Spieler keine spielbaren Steine mehr hat

**Comment by jstsddg** [comment]
Hmm okay, i guess. Ich hätte gedacht, dass die `value` Funktion vorher `finished(s)` aufruft, aber dem ist anscheinend nicht so.

**Comment by benfu99** [comment]
Das tut sie, nur fängt finished(s) diesen Fall halt nicht ab^^
