### ISSUE TITLE
Project: Anti-Pattern entfernen

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#64]
Vergleiche auf `True` oder `False` sollen entfernt werden:
* Tests der Form `if enable == True` können zu `if enable` vereinfacht werden.

**Comment by nclskfm** [comment]
In `nmm-gui` habe ich die anti pattern bereits im pr #52 entfernt.

**Comment by jstsddg** [comment]
@nclskfm Konnte gerade nichts finden, habe alles durchgeschaut. Ich schließe das Issue
