### ISSUE TITLE
Add blacklisted States

### ISSUE THREAD

**Issue by nclskfm** [nclskfm/dhbw-studienarbeit-muehle#91]
Wenn KI vs. KI spielt, kommen sie irgendwann in einen Zyklus:

![image](https://user-images.githubusercontent.com/52164046/107674492-4f3a1480-6c97-11eb-8f9e-6733c4b60e38.png)

Damit das nicht mehr vorkommt, sollten besuchte States gespeichert werden, damit die KI diese nicht mehr spielt

**Comment by jstsddg** [comment]
Ich finde das Bild genial :D

**Comment by nclskfm** [comment]
Danke, hab mir Mühe gegeben xD
