### ISSUE TITLE
GUI: Remis Erkennung

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#96]
Die GUI soll eine Remis Erkennung bekommen, bei der nach der n-ten Wiederholung eines States automatisch ein Remis erklärt wird.
_Ursprünglicherweise war eine einfache Wiederholung angedacht, eine einstellbare Option wäre aber schöner_

**Comment by nclskfm** [comment]
widerspricht sich das nicht mit der `visible` Implementierung von @benfu99 im letzten Sprint?

**Comment by nclskfm** [comment]
sollte die denn wieder entfernt werden?

**Comment by jstsddg** [comment]
@nclskfm ich finde, dass man das als toggle behalten kann, also standardmäßig ist das aus, aber damit wir das weiterhin einschalten können um zu debuggen

**Comment by nclskfm** [comment]
Unentschieden, wenn:
- ein State x mal gespielt worden ist
- wenn x Züge keine Mühle geschlagen worden ist
