### ISSUE TITLE
Meta: Auswahl von zusätzlicher Aufgabe

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#98]
Da wir drei Studenten an der Studienarbeit sind, sollen wir eine weiterführende Aufgabe lösen. Jetzt müssen wir uns entscheiden, welche wir durchführen wollen:
* Caching von Symmetrien
* Eröffnungsbibliothek
  * Siehe erstes Paper in Kapitel `Machine Learning`
* Retrograde Analysis

Wenn wir uns rein gelesen haben und uns entschieden haben, müssen wir neue Issues anlegen und implementieren.

**Comment by jstsddg** [comment]
Die Symmetrie Erkennung wurde in #103 implementiert, bietet jedoch nur in den ca. ersten 3 Zügen einen vorteil.

**Comment by nclskfm** [comment]
- @benfu99 und ich wollen retrograde analysis im Rahmen der Klausurleistung in wissensbasierte Systeme machen
- @jstsddg wollte am Montag fragen, ob er die Startzustände in Mühle in Wissensbasierte Systeme untersuchen kann

Dann würde für die Studienarbeit nur noch Symmetrie-Erkennung offen bleiben (aber vielleicht kann man die Implementierung von Joost noch verbessern...)

**Comment by jstsddg** [comment]
@nclskfm Noch mehr verbessern? Ich fühle mich beleidigt! :P
Ich glaube bevor wir die Symmetrie nochmal anfassen, sollten wir alles zu Bitmaps ändern... Da ist dann die Frage, ob wir aber nicht direkt eine andere Sprache nehmen sollen, die insgesamt schneller ist...

PS: Ich habe aus Spaß eine Rust Implementierung angefangen, aber ist nicht so leicht wie ich dachte. Die Bitmaps machen mich fertig... Pro Rust: Man kann Python Bindings erzeugen lassen oder zu WASM compilieren, Contra Rust: Ist nicht die einfachste Programmiersprache anzufangen, aber es macht echt Spaß, wenn man sich etwas rein fuchst!

**Comment by nclskfm** [comment]
> Noch mehr verbessern? Ich fühle mich beleidigt! :P

Ja ne. Aber vielleicht das man das halt anders speichert, also immer nur eine Version. Aber das Speichern kostet ja auch nicht so wirklich was haben wir mal geschaut. 
Ich finde deine Implementierung immer noch 🤯😂

> Ich glaube bevor wir die Symmetrie nochmal anfassen, sollten wir alles zu Bitmaps ändern... Da ist dann die Frage, ob wir aber nicht direkt eine andere Sprache nehmen sollen, die insgesamt schneller ist...
> 
> PS: Ich habe aus Spaß eine Rust Implementierung angefangen, aber ist nicht so leicht wie ich dachte. Die Bitmaps machen mich fertig... Pro Rust: Man kann Python Bindings erzeugen lassen oder zu WASM compilieren, Contra Rust: Ist nicht die einfachste Programmiersprache anzufangen, aber es macht echt Spaß, wenn man sich etwas rein fuchst!

Ja es wäre auch echt cool, wir haben nur noch einen Monat und schon voll viel Zeit rein investiert 🥺

Wir haben halt auch noch die ganzen anderen (Haus)-arbeiten... 😑

**Comment by jstsddg** [comment]
> Ja ne. Aber vielleicht das man das halt anders speichert, also immer nur eine Version. Aber das Speichern kostet ja auch nicht so wirklich was haben wir mal geschaut.
> Ich finde deine Implementierung immer noch exploding_headjoy

War auch nur ein Spaß ;)
Ja nach meiner Analyse ist das Problem auch wirklich nur das errechnen, da dort die ganzen Tupeln etc. erstellt werden müssen - das eigentliche speichern im Cache ist zu vernachlässigen. Das Problem können wir aber wie gesagt nur durch eine andere Speichermöglichkeit lösen.

Danke danke :D Ich habe mich einfach mit einem Stift und Papier hin gesetzt und versucht ein Muster zu finden, das hat wohl auch geklappt ;)

> Ja es wäre auch echt cool, wir haben nur noch einen Monat und schon voll viel Zeit rein investiert pleading_face
> 
> Wir haben halt auch noch die ganzen anderen (Haus)-arbeiten... expressionless

Ja das stimmt, sehe ich auch so. Das sollten wir dann auch genau so mal ansprechen. Mit Rust habe ich auch nur angefangen, weil ich die Sprache lernen wollte. Die Motivation kommt auch nur in Schüben.. :joy:

**Comment by benfu99** [comment]
Also ich muss auch zugeben, die Motivation jetzt noch Rust zu lernen hält sich in Grenzen :D

Was ist denn eigentlich aus dem ursprünglichen "Zusatzthema" Endspieldatenbank geworden? Letztendlich erzeugen Niclas und Ich ja "nur" die Rohprodukte für diese Datenbank. Möglicherweise könnte dann vielleicht die Einbindung der erzeugten Datenbank ein auch nicht zu unterschätzender Faktor sein.

Ich denke da müssen wir aber generell nochmal die genauere Aufgabenstellung von Stroetmann zu dem Thema abwarten/nachfragen.

**Comment by jstsddg** [comment]
Wir sollten ihn denke ich einfach mal Fragen, was er noch erwartet. Symmetrie haben wir ja wie gesagt bereits implementiert.

**Comment by jstsddg** [comment]
Ich schließe das Issue, da wir alles gemacht haben, soweit wir können. Den Rest müssen wir mit Stroetmann klären.
